name: Package Helm ECR
description: Package a helm chart and deploy to an AWS ECR repository using OCI
branding:
  icon: hard-drive
  color: blue
inputs:
  aws-access-key-id:
    description: The AWS access Key id
    required: true
  aws-secret-access-key:
    description: The AWS access key
    required: true
  aws-region:
      description: The AWS region, default eu-west-1
      default: eu-west-1
      required: false
  ecr-repo-name:
      description: ECR Repo name to create/deploy to
      default: eu-west-1
      required: false
  chart-path:
    description: the directory path to the specified chart
    required: true
runs:
  using: "composite"
  steps:
    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1.0.3

    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to ECR
      id: ecr
      uses: elgohr/ecr-login-action@v3
      with:
        access_key: ${{ inputs.aws-access-key-id }}
        secret_access_key: ${{ inputs.aws-secret-access-key }}
        region: ${{ inputs.aws-region }}

    - name: Create AWS ECR Repository if it does not exist
      shell: bash
      env:
        ECR_REPOSITORY: ${{ inputs.ecr-repo-name }}
      run: |
        aws ecr describe-repositories --repository-names $ECR_REPOSITORY || aws ecr create-repository --repository-name $ECR_REPOSITORY

    - name: Install PyBump
      run: |
        python3 -m pip install pybump
      shell: bash
    - name: Helm Chart
      env:
          ECR_REGISTRY: ${{ steps.ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecr-repo-name }}
          HELM_EXPERIMENTAL_OCI: "1"
      run : |
        version=$(pybump get --file ${{ inputs.chart-path }}/Chart.yaml)
        helm package \
        ${{ inputs.chart-path }} \
        --app-version $version \
        --version $version
        echo pushing $(basename ${{ inputs.chart-path }})-$version.tgz to oci://$ECR_REGISTRY
        helm push $(basename ${{ inputs.chart-path }})-$version.tgz oci://$ECR_REGISTRY
      shell: bash
